// <auto-generated />
using ConsentApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231020103054_UpdateStudyAndPatient")]
    partial class UpdateStudyAndPatient
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConsentApp.Data.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("IdType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("ConsentApp.Data.Entities.Study", b =>
                {
                    b.Property<string>("StudyId")
                        .HasColumnType("text");

                    b.HasKey("StudyId");

                    b.ToTable("Studies");
                });

            modelBuilder.Entity("PatientStudy", b =>
                {
                    b.Property<int>("PatientsId")
                        .HasColumnType("integer");

                    b.Property<string>("StudiesStudyId")
                        .HasColumnType("text");

                    b.HasKey("PatientsId", "StudiesStudyId");

                    b.HasIndex("StudiesStudyId");

                    b.ToTable("PatientStudy");
                });

            modelBuilder.Entity("PatientStudy", b =>
                {
                    b.HasOne("ConsentApp.Data.Entities.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsentApp.Data.Entities.Study", null)
                        .WithMany()
                        .HasForeignKey("StudiesStudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
